security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\ApiAuthenticator

            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /
                always_remember_me: false

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user/profile, roles: ROLE_USER }
        - { path: ^/user/update, roles: ROLE_USER }
        - { path: ^/user/delete, roles: ROLE_ADMIN }
        - { path: ^/product/checkout, roles: ROLE_USER }
